# gcloud builds submit --config=cloudbuild.yaml .
steps:
  - id: '1 Run dbt'
    name: 'fishtownanalytics/dbt:1.0.0'
    entrypoint: 'bash'
    args:
      - '-c'
      - |-
         pwd
         ls
         xdg-open /workspace/profiles/profiles.yml
         export DBT_PROFILES_DIR=./profiles/profiles.yml
         dbt debug --config-dir
         dbt deps --profiles-dir .
         if [[ $? == 1 ]]; then
          echo '1'
          exit 1
         fi
         dbt debug --target ${_DBT_TARGET} --profiles-dir .
         if [[ $? == 1 ]]; then
          echo '1'
          exit 1
         fi
         dbt run --target ${_DBT_TARGET} --profiles-dir .
         if [[ $? == 1 ]]; then
          echo '1'
          exit 1
         fi
         dbt test --data --target ${_DBT_TARGET} --profiles-dir .
         if [[ $? == 1 ]]; then
          echo '1'
          exit 1
         fi       
    timeout: 1200s
  