dbt_airbnb_prod:
  outputs:
    dev:
      dataset: airbnb
      job_execution_timeout_seconds: 30
      job_retries: 1
      method: oauth
      priority: interactive
      project: dbt-airbnb-prod
      threads: 4
      type: bigquery
  target: dev